language: python
python:
  - "3.6"

os: linux

services:
   - docker

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
    - $HOME/.cache

env:
  matrix:
    - COMPILER_NAME=clang COMPILER_VERSION=5.0
    - COMPILER_NAME=clang COMPILER_VERSION=6.0
    - COMPILER_NAME=clang COMPILER_VERSION=7
    - COMPILER_NAME=clang COMPILER_VERSION=8
    - COMPILER_NAME=clang COMPILER_VERSION=9
    - COMPILER_NAME=gcc COMPILER_VERSION=7
    - COMPILER_NAME=gcc COMPILER_VERSION=8
    - COMPILER_NAME=gcc COMPILER_VERSION=9

notifications:
  email:
    recipients:
      - michel.estermann@bbv.ch
    on_success: change
    on_failure: always

install: skip

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo ${TRAVIS_PULL_REQUEST_BRANCH}; fi`
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then python rebuild_and_upload.py --upload --tag ${TAG} --build_number $TRAVIS_BUILD_NUMBER --${COMPILER_NAME} ${COMPILER_VERSION}; else python rebuild_and_upload.py --upload --tag ${TAG} --${COMPILER_NAME} ${COMPILER_VERSION}; fi
