name: CI

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        # shortcut for common versions 
        compiler: [clang, gcc]
        compiler-version: [7, 8 , 9]
        # include extra clang versions
        include:
          - compiler: clang
            compiler-version: 5.0
          - compiler: clang
            compiler-version: 6.0

    steps:
      - uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}
          logout: true

      - name: Set output variables
        id: vars
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
          echo ::set-output name=sha_short::$(git rev-parse --short HEAD)

      - name: Check output variables
        run: |
          echo ${{ steps.vars.outputs.tag }}
          echo ${{ steps.vars.outputs.sha_short }}

      - name: build branch without pushing
        # Push to arbitrary feature branch will not push the image
        if: github.event.action != 'published' && github.ref != 'refs/heads/master'
        run : |
          python rebuild_and_upload.py --${{ matrix.compiler }} ${{ matrix.compiler-version }} --tag ${{ steps.vars.outputs.sha_short }} --build_number $GITHUB_RUN_NUMBER
      - name: build main and push to dockerhub
        # Push to master will push the image to master
        if: github.event.action != 'published' && github.ref == 'refs/heads/master'
        run : |
          python rebuild_and_upload.py --${{ matrix.compiler }} ${{ matrix.compiler-version }} --tag latest --build_number $GITHUB_RUN_NUMBER --upload