name: CI/CD

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}

      - name: Set output variables
        id: vars
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
          echo ::set-output name=sha_short::$(git rev-parse --short HEAD)

      - name: Check output variables
        run: |
          echo ${{ steps.vars.outputs.tag }}
          echo ${{ steps.vars.outputs.sha_short }}

      - name: build branch without pushing
        # Push to arbitrary feature branch
        if: github.event.action != 'published' && github.ref != 'refs/heads/main'
        run : |
          python rebuild_and_upload.py --gcc 9 --tag ${{ steps.vars.outputs.sha_short }} --build_number $GITHUB_RUN_NUMBER
      - name: build main and push to dockerhub
        # Push to main
        if: github.event.action != 'published' && github.ref == 'refs/heads/main'
        run : |
          python rebuild_and_upload.py --gcc 9 --tag latest --build_number $GITHUB_RUN_NUMBER --upload