name: Build and publish docker images using the script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-common-images:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        compiler-version: [7, 8, 9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DockerHubUsername }}
        password:  ${{ secrets.DockerHubPassword }}
    - name: run rebuild_and_upload.py
      run: |
         # Strip git ref prefix from version
         VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
         # Strip "v" prefix from tag name
         [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
         
         # Use Docker `latest` tag convention
         [ "$VERSION" == "master" ] && VERSION=latest
         ./rebuild_and_upload.py --upload --tag ${VERSION} --${{ matrix.compiler }} ${{ matrix.compiler-version }}

  build-additional-clang-images:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang]
        compiler-version: [5.0, 6.0]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DockerHubUsername }}
        password:  ${{ secrets.DockerHubPassword }}
    - name: run rebuild_and_upload.py
      run: |
         # Strip git ref prefix from version
         VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
         # Strip "v" prefix from tag name
         [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
         
         # Use Docker `latest` tag convention
         [ "$VERSION" == "master" ] && VERSION=latest
         ./rebuild_and_upload.py --upload --tag ${VERSION} --${{ matrix.compiler }} ${{ matrix.compiler-version }}
      

